### ISSUE TITLE
set-output deprecation warning when running the action

### ISSUE THREAD

**Issue by zkoppert** [jonabc/licensed-ci#203]
Hey there! 

I'm noticing a log annotation when running the action:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I checked out the linked blog article and from what I can tell in the code, the [set-output code path](https://github.com/jonabc/licensed-ci/blob/main/dist/index.js#L973) is never used, and core.setOutput() is used instead. The blog notes that the @actions/core version should be v1.10 or greater so you should be functionally using the new (non-deprecated) `setOutput()` function.

My best guess at fixing this warning is to remove [dist/index.js#L964-L975](https://github.com/jonabc/licensed-ci/blob/main/dist/index.js#L964-L975) and check if the warning is resolved. 

Does that sound reasonable? If so, I can open up a PR.

**Comment by zkoppert** [comment]
Looks like deleting the code is yielding an error:
> Error: core.setOutput is not a function

So I am assuming that was the definition of core.setOutput... oops. Back to the drawing board.

**Comment by jonabc** [comment]
`dist/index.js` is auto-generated as a precommit hook setup with `husky` though and shouldn't be edited manually.  It looks like though dependabot did update the `@actions/core` dependency to the latest version that uses the new `setOutput` implementation, the `dist/index.js` file wasn't updated.

This kind've highlights a friction point I've seen in the past with dependabot where dependabot changes don't trigger secondary effects (like generating files after changes). 

In this case I think a full fix looks like
1. fix the immediate issue - run `npm run package` to [trigger a rebuild](https://github.com/jonabc/licensed-ci/blob/c6264d6d1d75165372dbd37d2e02f6eff8b9972b/package.json#L9) of that file and commit the result.
1. fix future instances where index.js isn't updated after a dependabot update - maybe adding a `postinstall: npm run package` package.json script would get triggered after a dependabot update?  otherwise we'll need to figure out how to make sure that whatever dependabot does when updating dependencies triggers a re-generation of `dist/index.js`

**Comment by zkoppert** [comment]
That makes sense. Thanks for explaining that. Also wish that auto generated code always inserted a header. 😵‍💫 

I'll run through those steps.

**Comment by zkoppert** [comment]
https://github.com/jonabc/licensed-ci/pull/204
