### ISSUE TITLE
Dealing with PRs created after licensed has created a fixup PR

### ISSUE THREAD

**Issue by mhagger** [jonabc/licensed-ci#48]
This came up recently:

1. A colleague pushed a branch (call it `B`)
2. The licensed-ci action ran and created a PR to update the license cache
3. The colleague created a PR based on branch `B`
4. The colleague noticed that CI was failing on their PR due to the license cache problem, but didn't notice that there was already an automatically-created PR fixing the problem. As a result, they didn't know how to proceed.

As I understand it, if (3) had happened before (2), then the action would have created a comment on the PR explaining what to do. But since (2) happened before (3), there was no PR to add such a comment to, so there was no obvious breadcrumb in the PR pointing at the solution.

One idea for improving this situation would be also to run the Action when PRs are created, and if there are any license-fixup branches pending against the new PR's head branch, to add the informative comment to the PR then.

/cc @jonabc, who asked me to create this issue.

Cheers!

**Comment by jonabc** [comment]
Yeah this is an interesting problem, in that to get this new behavior users _must_ run the action from `pull_request` events.  If that's the case, then running on both the `pull_request.synchronize` event action and the `push` event poses an interesting problem of whether users will get multiple concurrent runs of the action and how that will manifest in action results.

My concern is a flow like the following, assuming a PR already exists on a branch that receives a push:
- push event triggers an action execution
- roughly simultaneously the pull_request.synchronize event type triggers an action execution
- they each create a branch locally, do all the normal licensed-ci operations and try to push the new branch
- one of them 💥  because the local branch history doesn't match whats on the remote and licensed-ci doesn't force push 

I'll have to look at whether 
- actions know to only run one or the other if both event types are specified 
- a failure and a success from the action on a single commit would block merge if the PR has any applicable branch protection rules that require the action to pass
   - if the two event types are tracked as separate action results and both are marked required that's would also cause problems

If this is an issue the only real workaround I can think of is to explicitly ignore the `pull_request.synchronize` event type and document the reason.

**Comment by jonabc** [comment]
@mhagger coming back to this issue as well, I've started using this actions workflow `on:` pattern in my repos.  Care to give it a try and see how it works?  If it solves the problems you're having then I can change the examples in the README here and promote the new pattern.

```yml
name: Verify cached license metadata

on:
  # run on pushes to main/default branch
  push:
    branches:
      - main
  # run on pull request events where contents might have changed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # run on demand
  workflow_dispatch:
```

**Comment by jonabc** [comment]
I've updated the readme examples to ☝️ suggested trigger events
